import type { Metadata } from 'next';
import '@styles/globals.css';
import Header from '@components/layouts/Header';
import Footer from '@components/layouts/Footer';

export const metadata: Metadata = {
  title: 'NFT App',
  description: 'Generated by NEXT.js',
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='text-base overflow-x-hidden max-w-[100em] m-auto w-screen'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
